### ISSUE TITLE
Remove polygons with centroids outside of the tile

### ISSUE THREAD

**Issue by laurenwalker** [PermafrostDiscoveryGateway/viz-3dtiles#8]
From @robyngit :

> for 3d tile purposes, you will want to remove polygons that are duplicated between tiles. (Duplicated because they intersect more than one tile, and are included in all the tiles they intersect). Just filter out the polygons where centroid_within_tile is false, i.e. gdf = gdf[gdf['centroid_within_tile'] == True]

> The staged files are trimmed to the tile shape, but for the purpose of rasterization, each tile file contains all the polygons that intersect at all with the tile. For 3D tile making, I think what you want is for each tile to contain all the polygons that have a centroid that falls with-in the tile. That’s why you need to filter by centroid_within_tile

**Comment by robyngit** [comment]
For more info about the output of staged files, see https://github.com/PermafrostDiscoveryGateway/viz-staging/tree/develop#readme

Also note that this is _not_ referring to the [duplication problem caused by overlapping input files](https://github.com/PermafrostDiscoveryGateway/viz-staging/issues/1)
